import { ThemeProvider } from "@/providers/ThemeProvider";
import "@/styles/globals.css";
import { SiteHeader } from "@/components/SiteHeader";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/Footer";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { TailwindIndicator } from "@/components/TailwindIndicator";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "@/app/themes.css";
import { siteConfig } from "@/config/site";
import { Inter as FontSans } from "next/font/google";
import { Metadata } from "next";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeSwitcher />

          <div className="mt-16">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
